### ISSUE TITLE
Roku external control has been updated for better search

### ISSUE THREAD

**Issue by jpkilman** [julianh2o/RokuAlexaLambdaSkill#19]
I am new to working with API's and any sort of programming (taken a couple javascript classes).  I noticed that roku added some direct search calls to their API.  This would be a better way to accomplish the search instead of having to count how many down clicks you hit to get to search.  My initial testing has shown it is faster as well since you don't have to build any waiting time in to the command. I'm working to get this updated in the code and if I'm successful (again limited experience) I will post it on this site. 

Here is the documentation for anyone interested...  only supported in firmware version 7.5 on the roku. https://sdkdocs.roku.com/display/sdkdoc/External+Control+Guide#ExternalControlGuide-searchExamples

**Comment by julianh2o** [comment]
Cool! Good find, I was wondering how long it would take them to implement something a bit better to use for searching!

**Comment by BillOatman** [comment]
Any progress on this?

**Comment by mikehobi** [comment]
@BillOatman I've been looking into this and might have a PR soon.

There are a few caveats with the Search API though, it won't auto play a video unless it is an "exact" match. So searching for "Always Sunny" instead of "It's Always Sunny in Philadelphia" will not auto-play. Also if there are multiple versions of a movie / tv show like "Fargo", it will not auto-play.

The simplest version I have working allows for a `title` and `rokuChannel`, but more specific keywords would get a little tricky like "Play Breaking Bad season 2 on Netflix"

**Comment by mikehobi** [comment]
@BillOatman Just posted a pull request to implement the search.
